yatube/about/urls.py
from django.views.generic.base import TemplateView
from django.urls import path

app_name = 'about'

urlpatterns = [
    path(
        'author/',
        TemplateView.as_view(template_name='about/author.html'),
        name='author',
    ),
    path(
        'tech/',
        TemplateView.as_view(template_name='about/tech.html'),
        name='tech'
    ),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(
        '',
        views.IndexView.as_view(),
        name='index'
    ),
    path(
        'group/<slug:slug>/',
        views.GroupView.as_view(),
        name='group_list',
    ),
    path(
        'profile/<str:username>/',
        views.ProfileView.as_view(),
        name='profile',
    ),
    path(
        'posts/<int:post_id>/',
        views.PostDetailView.as_view(),
        name='post_detail',
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.PostEditView.as_view(),
        name='post_edit'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.AddCommentView.as_view(),
        name='add_comment'
    ),
    path(
        'create/',
        views.PostCreateView.as_view(),
        name='post_create'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

yatube/templates/includes/footer.html
<p>
  © {{ year }} Copyright <span style="color:red">Ya</span>tube
</p>

yatube/templates/includes/form.html
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        {{ header }}
      </div>
      <div class="card-body">
        {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endif %}
        <form method="post"
          {% if action_url %}
            action="{% url action_url %}"
          {% endif %}
          {% if for_image %}
            enctype="multipart/form-data"
          {% endif %}
        >
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group row my-3 p-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>
              {{ field|addclass:'form-control' }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              {{ button }}
            </button>
            {% if additional_button_url and additional_button_text %} 
              <a href="{% url additional_button_url %}" class="btn btn-link">
                {{ additional_button_text }}
              </a>
            {% endif %}
          </div>
        </form>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light" 
  style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static "img/logo.png" %}" width="30" height="30"
        class="d-inline-block align-top" alt="" />
      <span style="color:red">Ya</span>tube
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent" 
      aria-controls="navbarSupportedContent" 
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills ms-auto mb-2 mb-lg-0 flex-column flex-lg-row">
          <li class="nav-item"> 
            <a class="nav-link 
              {% if view_name == 'about:author' %}active{% endif %}"
              href="{% url 'about:author' %}"
            >Об авторе</a>
          </li>
          <li class="nav-item">
            <a class="nav-link
              {% if view_name == 'about:tech' %}active{% endif %}"
              href="{% url 'about:tech' %}"
            >Технологии</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item"> 
              <a class="nav-link 
                {% if view_name == 'posts:post_create' %}active{% endif %}"
                href="{% url 'posts:post_create' %}"
              >Новая запись</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light 
                {% if view_name == 'users:password_change_form' %}active{% endif %}"
                href="{% url 'users:password_change_form' %}"
              >Изменить пароль</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light 
                {% if view_name == 'users:logout' %}active{% endif %}"
                href="{% url 'users:logout' %}"
              >Выйти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light 
                {% if view_name == 'posts:profile' %}active{% endif %}"
                href="{% url 'posts:profile' user %}"
              >Пользователь: {{ user.username }}</a>
            </li>
          {% else %}
            <li class="nav-item"> 
              <a class="nav-link link-light 
                {% if view_name == 'users:login' %}active{% endif %}"
                href="{% url 'users:login' %}"
              >Войти</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light 
                {% if view_name == 'users:signup' %}active{% endif %}" 
                href="{% url 'users:signup' %}"
              >Регистрация</a>
            </li>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </div>
</nav>