yatube/about/urls.py
from django.views.generic.base import TemplateView
from django.urls import path

app_name = 'about'

urlpatterns = [
    path(
        'author/',
        TemplateView.as_view(template_name='about/author.html'),
        name='author',
    ),
    path(
        'tech/',
        TemplateView.as_view(template_name='about/tech.html'),
        name='tech'
    ),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(
        '',
        views.IndexView.as_view(),
        name='index'
    ),
    path(
        'group/<slug:slug>/',
        views.GroupView.as_view(),
        name='group_list',
    ),
    path(
        'profile/<str:username>/',
        views.ProfileView.as_view(),
        name='profile',
    ),
    path(
        'posts/<int:post_id>/',
        views.PostDetailView.as_view(),
        name='post_detail',
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.PostEditView.as_view(),
        name='post_edit'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.AddCommentView.as_view(),
        name='add_comment'
    ),
    path(
        'create/',
        views.PostCreateView.as_view(),
        name='post_create'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse_lazy

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    """Model for a group of posts."""

    title = models.CharField(
        max_length=200,
        verbose_name='Название',
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='ЧПУ',
    )
    description = models.TextField(
        verbose_name='Описание',
    )

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self) -> str:
        return f'{self.title}'


class Post(CreatedModel):
    """Model for posts."""

    text = models.TextField(
        verbose_name='Текст',
        help_text='Текст поста',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа поста',
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True,
    )

    def get_absolute_url(self):
        return reverse_lazy('posts:post_detail', args=(self.pk,))

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-created',)

    def __str__(self):
        return f'{self.text[:15]}'


class Comment(CreatedModel):
    """Model of comments."""

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Пост',
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
    )
    text = models.TextField(
        verbose_name='Текст',
        help_text='Текст нового комментария',
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f'{self.text}'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['placeholder'] = (
            'Текст'
        )
        self.fields['group'].empty_label = (
            'Группа еще не выбрана'
        )

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Введите текст',
            'group': 'Выберите группу',
        }
        help_texts = {
            'text': 'Текст поста',
            'group': 'Группа, к которой будет относиться пост',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormMixin, CreateView
from django.views.generic import UpdateView
from django.views.generic.list import ListView
from django.views.decorators.cache import cache_page
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator

from core.views import DetailListView
from .forms import PostForm, CommentForm
from .models import User, Group, Post


@method_decorator(cache_page(20, key_prefix='index_page'), name='dispatch')
class IndexView(ListView):
    model = Post
    template_name = 'posts/index.html'
    paginate_by = settings.POSTS_PER_PAGE


class GroupView(DetailListView):
    template_name = 'posts/group_list.html'
    general_object_model = Group
    general_object_context_name = 'group'
    relate_objects_name = 'posts'


class ProfileView(DetailListView):
    template_name = 'posts/profile.html'
    slug_url_kwarg = 'username'
    slug_field = 'username'
    general_object_model = User
    general_object_context_name = 'author'
    relate_objects_name = 'posts'


class PostDetailView(FormMixin, DetailView):
    form_class = CommentForm
    model = Post
    slug_url_kwarg = 'post_id'
    slug_field = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.get_object().comments.all()
        return context


class PostCreateView(LoginRequiredMixin, CreateView):
    template_name = 'posts/create_post.html'
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('posts:profile', args=(self.request.user,))


class PostEditView(LoginRequiredMixin, UpdateView):
    template_name = 'posts/create_post.html'
    model = Post
    form_class = PostForm
    pk_url_kwarg = 'post_id'

    def get(self, request, *args, **kwargs):
        if self.get_object().author != self.request.user:
            return redirect(self.get_object())
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('posts:post_detail', args=(self.get_object().pk,))


class AddCommentView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = CommentForm
    pk_url_kwarg = 'post_id'

    def get(self, request, *args, **kwargs):
        return redirect(self.get_object())

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = self.get_object()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('posts:post_detail', args=(self.get_object().pk,))

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Новая запись
  {% endif %}
{% endblock title %}
{% block content %}
  {% if request.resolver_match.view_name == "posts:post_create" %}
    {% include "includes/form.html" with header="Новая запись" button="Добавить" for_image=True %}
  {% else %}
    {% include "includes/form.html" with header="Редактировать запись" button="Сохранить" for_image=True %}
  {% endif %}
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock title %}
{% block content %}
  <h1>{{ group.title }}</h1>
  {{ group.description|linebreaks }}
  {% for post in object_list %}
    {% include "posts/includes/post.html" with show_author=True %}
  {% endfor %}
  {% include "posts/includes/paginator.html" %}
{% endblock content %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}
  Последние обновления на сайте
{% endblock title %}
{% block content %}
  <h1>Последние обновления на сайте</h1>
  {% for post in object_list %}
    {% include "posts/includes/post.html" with show_group_link=True show_author=True %}
  {% endfor %}
  {% include "posts/includes/paginator.html" %}
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}
  Пост {{ post.text|slice:"30" }}
{% endblock title %}
{% block content %}
  {% load thumbnail %}
  {% load user_filters %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.created|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа:
            <a href="{% url "posts:group_list" post.group.slug %}">
              {{ post.group }}
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор:
          <a href="{% url "posts:profile" post.author.username %}">
            {{ post.author.get_full_name }}
          </a>
        </li>
        <li class="list-group-item d-flex 
          justify-content-between align-items-center">
          Всего постов автора: <span>{{ post.author.posts.count }}</span>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="" />
      {% endthumbnail %}
      <p>
        {{ post.text|linebreaks }}
      </p>
      {% if request.user == post.author %}
        <a class="btn btn-primary" href="{% url "posts:post_edit" post.id %}">
          Редактировать запись
        </a>
      {% endif %}
      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url "posts:add_comment" post.id %}">
              {% csrf_token %}      
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}
      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url "posts:profile" comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
            <p>
              {{ comment.text }}
            </p>
          </div>
        </div>
      {% endfor %}
    </article>
  </div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock title %}
{% block content %}
  <h1>Все посты пользователя {{ author.get_full_name }}</h1>
  <h3>Всего постов: {{ author.posts.count }}</h3>
  {% for post in page_obj %}
    {% include "posts/includes/post.html" with show_group_link=True %}
  {% endfor %}
  {% include "posts/includes/paginator.html" %}
{% endblock content %}